config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :clients
  resources :developers do 
    get 'detail', on: :member
  end
  resources :projects
  resources :teches
  resources :careers do
    resources :job_submissions
  end
  devise_for :users
  resources :post_categories
  resources :posts

  get 'home', to: 'home#index'
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :post_categories, path: 'post-categories' do
        member do
          get 'filter-post-by-category', to: :filter_post_by_category
        end

        collection do
          get 'category-list', to: :category_list
        end
      end

      resources :posts, only: %i[index show] do
        member do
          get 'related-posts', to: :related_posts
        end
      end

      resources :careers, only: %i[index show]
      resources :job_submissions
      resources :subscriptions
    end
  end
end

app/models/tech.rb
# == Schema Information
#
# Table name: teches
#
#  id         :bigint           not null, primary key
#  name       :string
#  tech_type  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tech < ApplicationRecord
  enum tech_type: { frontend: 0, backend: 1, db: 2 }
  has_and_belongs_to_many :projects
  has_many :developer_teches
  has_many :developers, through: :developer_teches
  validates :name, presence: true, uniqueness: true
  validates :tech_type, presence: true
end

app/controllers/teches_controller.rb
class TechesController < ApplicationController
  before_action :set_tech, only: %i[show edit update destroy]

  def index
    if params[:tech_type].present?
      @current_type = params[:tech_type]
      @teches = Tech.where('tech_type = ?', params[:tech_type])
    else
      @teches = Tech.all
    end
    @pagy, @teches = pagy(@teches, items: per_page)
  end

  def show
    @pagy, @teches = pagy(Tech, items: per_page)
  end

  def new
    @tech = Tech.new
  end

  def edit; end

  def create
    @tech = Tech.new(tech_params)

    respond_to do |format|
      if @tech.save
        format.html { redirect_to @tech, notice: 'Tech was successfully created.' }
        format.json { render :show, status: :created, location: @tech }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tech.update(tech_params)
        format.html { redirect_to @tech, notice: 'Tech was successfully updated.' }
        format.json { render :show, status: :ok, location: @tech }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tech.destroy
    respond_to do |format|
      format.html { redirect_to teches_url, notice: 'Tech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_tech
    @tech = Tech.find(params[:id])
  end

  def tech_params
    params.require(:tech).permit(:name, :tech_type)
  end
end

app/views/teches/_form.html.slim
.section
  = simple_form_for @tech do |f|
    .field.mt-2.mb-3
      .control
        = f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
      = f.label :tech_type
      = f.select :tech_type, Tech.tech_types.keys, { }, { class: "select2 form-control" }
    = f.button :submit, class: "btn btn-info mb-2"
    = link_to  "Back", :back, class:"btn btn-secondary mb-2 ml-4"

app/views/teches/edit.html.slim
- content_for :page_title, "Edit Post Category"
= render 'form'

app/views/teches/index.html.slim
.row
  .col-12
    .page-title-box
      .page-title-right
        ol.breadcrumb.m-0
          li.breadcrumb-item
            = link_to 'Home', root_path
          li.breadcrumb-item Technologies
      h4.page-title
        | Technology List

section.hero.is-primary.is-medium
  .hero-head
    nav.navbar
      .container
        .navbar-brand
        #navbarMenuHeroA.navbar-menu
          .navbar-end
            = link_to "Create New Technology", new_tech_path, class:"navbar-item"
  .hero-body
    .container.has-text-centered
      h1.title
        = yield :page_title

section.section
  .container
      .card
        .card-content
          .container
            .media
            .media-content
              .card-body
                h4.header-title.mb-2 Technologies
                = form_tag("/teches", method: 'get') do
                  .field.mb-3.float-md-right.mr-2
                    = select_tag(:tech_type, options_for_select(Tech.tech_types, :selected => @current_type ), {:prompt => "Select tech type",  onchange: "this.form.submit();"})
                  .field.mb-3.float-md-right
                    span.header-title.mr-3 style=("font-weight: bold;") Filter:    
                  .table-responsive-sm
                    table.table.table-centered.mb-0
                      tr
                        th scope="col" ID
                        th scope="col" TechName
                        th scope="col" TechType
                      - @teches.each do |tech|
                          tr
                            td = tech.id
                            td = link_to tech.name, tech
                            td = tech.tech_type
section.section
  .container.mb-3
    .d-flex.justify-content-center
      - if @teches.size > 0
        == pagy_bootstrap_nav(@pagy)

app/views/teches/new.html.slim
- content_for :page_title, "Create a new technology"
= render 'form'

app/views/teches/show.html.slim
- content_for :page_title, @tech.name
section.section
  .container.mb-4
    nav.level
      .level-left.mt-2
        p.level-item
          strong Actions
      .level-right.d-flex
        p.level-item.mr-3
          = link_to "Edit", edit_tech_path(@tech), class:"button btn btn-primary btn-sm"
        p.level-item.mr-3
          = link_to "Delete", tech_path(@tech), method: :delete, data: { confirm: "Are you sure?" }, class:"button btn btn-danger btn-sm"
        p.level-item
          = link_to  "Back", teches_path(page: @page), class:"button btn btn-dark btn-sm"
    hr/
    | Name:
    h4.title
      = @tech.name

    - if @teches.size > 0
      .container.mb-3
        .d-flex.justify-content-center
          == pagy_bootstrap_nav(@pagy)