config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :clients
  resources :developers do 
    get 'detail', on: :member
  end
  resources :projects
  resources :teches
  resources :careers do
    resources :job_submissions
  end
  devise_for :users
  resources :post_categories
  resources :posts

  get 'home', to: 'home#index'
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :post_categories, path: 'post-categories' do
        member do
          get 'filter-post-by-category', to: :filter_post_by_category
        end

        collection do
          get 'category-list', to: :category_list
        end
      end

      resources :posts, only: %i[index show] do
        member do
          get 'related-posts', to: :related_posts
        end
      end

      resources :careers, only: %i[index show]
      resources :job_submissions
      resources :subscriptions
    end
  end
end

app/models/pc.rb
# == Schema Information
#
# Table name: pcs
#
#  id           :bigint           not null, primary key
#  company_name :string           not null
#  full_name    :string           not null
#  level        :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Pc < ApplicationRecord
  has_many :pc_projects, dependent: :destroy
  has_many :projects, through: :pc_projects

  accepts_nested_attributes_for :pc_projects, allow_destroy: true

  validates :full_name, presence: true, uniqueness: true
  validates :company_name, presence: true, uniqueness: true
  validates :level, presence: true
end

app/controllers/pcs_controller.rb
class PcsController < ApplicationController
  before_action :set_pc, only: %i[show edit update destroy]
  before_action :set_project_options, only: %i[new edit]
  def index
    @pcs = Pc.all
    @pagy, @pcs = pagy_array(@pcs, items: per_page)
  end

  def show; end

  def new
    @pc = Pc.new
  end

  def edit; end

  def create
    @pc = Pc.new(pc_params)

    respond_to do |format|
      if @pc.save
        format.html { redirect_to @pc, notice: 'Pc was successfully created.' }
        format.json { render :show, status: :created, location: @pc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pc.update(pc_params)
        format.html { redirect_to @pc, notice: 'Pc was successfully updated.' }
        format.json { render :show, status: :ok, location: @pc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pc.destroy
    respond_to do |format|
      format.html { redirect_to pcs_url, notice: 'Pc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_pc
    @pc = Pc.find(params[:id])
  end

  def set_project_options
    @project_options = Project.pluck(:name, :id)
  end

  def pc_params
    params.require(:pc).permit({ project_ids: [] }, :full_name, :company_name, :level, pc_projects_attributes: %i[join_date id])
  end
end

app/views/pcs/_form.html.slim
.section
  = simple_form_for @pc do |f|
    .field.mt-2.mb-3
      .control
        = f.input :full_name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
      = f.input :company_name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
      = f.input :level, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
        = f.label :Project
        = f.select :project_ids, options_for_select(@project_options), { }, { class: "select2 form-control select2-multiple", :multiple => true, :size => 5, id: 'project-select' }
    .field.mt-2.mb-3
        h5.list Select the date pc join project
        = f.simple_fields_for :pc_projects do |ff|
          - project = ff.object.project 
          = project.name 
          br
          = ff.date_field :join_date
          br
    = f.button :submit, class: "btn btn-info mb-2"
    = link_to  "Back", :back, class:"btn btn-secondary mb-2 ml-4"
javascript:
  $('#project-select').select2();

app/views/pcs/edit.html.slim
- content_for :page_title, "Edit PC"
= render 'form'

app/views/pcs/index.html.slim
.row
  .col-12
    .page-title-box
      .page-title-right
        ol.breadcrumb.m-0
          li.breadcrumb-item
            = link_to 'Home', root_path
          li.breadcrumb-item PCs
      h4.page-title
        | PC List

section.hero.is-primary.is-medium
  .hero-head
    nav.navbar
      .container
        .navbar-brand
        #navbarMenuHeroA.navbar-menu
          .navbar-end
            = link_to "Create PC", new_pc_path, class:"navbar-item"
  .hero-body
    .container.has-text-centered
      h1.title
        = yield :page_title

section.section
  .container
      .card
        .card-content
          .container
            .media
            .media-content
              .card-body
                h4.header-title.mb-2 PC list 
                .table-responsive-sm
                  table.table.table-centered.mb-0
                    tr
                      th scope="col" ID
                      th scope="col" Full Name
                      th scope="col" Company Name
                      th scope="col" Level
                      th scope="col" Project
                      th scope="col" Join Date
                    - @pcs.each do |pc|
                        tr
                          td = pc.id
                          td = link_to pc.full_name, pc
                          td = pc.company_name
                          td = pc.level
                          td
                              - pc.projects.each do |p|
                                = link_to p.name, p
                                br
                          td
                            - pc.pc_projects.each do |pp|
                                = pp.join_date
                                br
section.section
  .container.mb-3
    .d-flex.justify-content-center
      - if @pcs.size > 0
        == pagy_bootstrap_nav(@pagy)

app/views/pcs/new.html.slim
- content_for :page_title, "Create a new pc"
= render 'form'

app/views/pcs/show.html.slim
- content_for :page_title, @pc.full_name
section.section
  .container.mb-4
    nav.level
      .level-left.mt-2
        p.level-item
          strong Actions
      .level-right.d-flex
        p.level-item.mr-3
          = link_to "Edit", edit_pc_path(@pc), class:"button btn btn-primary btn-sm"
        p.level-item.mr-3
          = link_to "Delete", pc_path(@pc), method: :delete, data: { confirm: "Are you sure?" }, class:"button btn btn-danger btn-sm"
        p.level-item
          = link_to  "Back", pcs_path(page: @page), class:"button btn btn-dark btn-sm"
    hr/
    | Full Name:
    h4.title
      = @pc.full_name
    | Company Name:
    h4.title
      = @pc.company_name
    | Level:
    h4.title
      = @pc.level