config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :clients
  resources :developers do 
    get 'detail', on: :member
  end
  resources :projects
  resources :teches
  resources :careers do
    resources :job_submissions
  end
  devise_for :users
  resources :post_categories
  resources :posts

  get 'home', to: 'home#index'
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :post_categories, path: 'post-categories' do
        member do
          get 'filter-post-by-category', to: :filter_post_by_category
        end

        collection do
          get 'category-list', to: :category_list
        end
      end

      resources :posts, only: %i[index show] do
        member do
          get 'related-posts', to: :related_posts
        end
      end

      resources :careers, only: %i[index show]
      resources :job_submissions
      resources :subscriptions
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  deployment  :string
#  description :string           not null
#  end_date    :date
#  git_repo    :string
#  industry    :integer
#  name        :string           not null
#  start_date  :date
#  trello      :string
#  website     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  client_id   :bigint
#
# Indexes
#
#  index_projects_on_client_id  (client_id)
#  index_projects_on_name       (name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (client_id => clients.id)
#
class Project < ApplicationRecord
  DAYS_FROM_NOW = [10, 30, 60].freeze
  enum industry: { sport: 0, ecommerce: 1, finance: 2, education: 3, manufacturing: 4, medical: 5, health_fitness: 6 }

  has_and_belongs_to_many :teches
  has_and_belongs_to_many :development_types
  has_many :developer_projects, dependent: :destroy
  has_many :developers, through: :developer_projects
  has_many :pc_projects, dependent: :destroy
  has_many :pcs, through: :pc_projects
  has_one_attached :image
  belongs_to :client

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :deployment, presence: true

  scope :filter_development_type, ->(development_type_ids) { where('development_type_id = ?', development_type_ids) }
  scope :filter_industry, ->(industry) { where('industry = ?', industry) }
  scope :search, ->(query) { where('lower(name) LIKE ? OR lower(deployment) LIKE ?', "%#{query.downcase}%", "%#{query.downcase}%") }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_technology_options
  before_action :prepare_projects, only: %i[index]
  def index
    filter_params
    project_filter
    @pagy, @projects = pagy(@projects, items: per_page)
  end

  def show
    @pagy, @projects = pagy(Project, items: per_page)
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def set_technology_options
    @frontend_options = Tech.frontend.pluck(:name, :id)
    @backend_options = Tech.backend.pluck(:name, :id)
    @db_options = Tech.db.pluck(:name, :id)
    @client_options = Client.pluck(:name, :id)
    @development_type_options = DevelopmentType.pluck(:name, :id)
  end

  def filter_params
    @development_type = params[:development_type_ids]
    @industry = params[:industry]
  end

  def project_filter
    @projects = @projects.search(params[:search]) if params[:search]
    if @development_type.present?
      @projects = @projects.joins(:development_types).filter_development_type(@development_type)
    end
    @projects = @projects.filter_industry(@industry) if @industry.present?
  end

  def project_params
    params.require(:project).permit(
      { tech_ids: [], development_type_ids: [] },
      :client_id,
      :name,
      :description,
      :deployment,
      :industry,
      :git_repo, :trello, :website, :image, :start_date, :end_date
    )
  end

  def prepare_projects
    @projects = Project.order(id: :desc)
  end
end

app/views/projects/_form.html.slim
.section
  = simple_form_for @project do |f|
    .field.mt-2.mb-3
      .control
        = f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
      .field.mt-2.mb-3
        = f.label :Client
        .control
          = f.select :client_id, @client_options
      .field.mt-2.mb-3
        = f.label :Frontend
        = f.select :tech_ids, options_for_select(@frontend_options), { }, { class: "select2 form-control select2-multiple", :multiple => true, :size => 5, id: "frontend-select" }
      .field.mt-2.mb-3
        = f.label :Backend
        = f.select :tech_ids, options_for_select(@backend_options), { }, { class: "select2 form-control select2-multiple", :multiple => true, :size => 5, id: "db-select" }        
      .field.mt-2.mb-3
        = f.label :Database
        = f.select :tech_ids, options_for_select(@db_options), { }, { class: "select2 form-control select2-multiple", :multiple => true, :size => 5, id: "backend-select" }        
      .field.mt-2.mb-3
        = f.input :deployment, 'data-provider': :summernote, class: 'form-control'
      .field.mt-2.mb-3
        = f.input :description, 'data-provider': :summernote, class: 'form-control'
      .field.mt-2.mb-3
        = f.input :git_repo, 'data-provider': :summernote, class: 'form-control'
      .field.mt-2.mb-3
        = f.input :trello, 'data-provider': :summernote, class: 'form-control'
      .field.mt-2.mb-3
        = f.input :website, 'data-provider': :summernote, class: 'form-control'
      .field.mt-2.mb-3
        = f.label :development_type
        = f.select :development_type_ids, options_for_select(@development_type_options), { }, { class: "select2 form-control select2-multiple", :multiple => true, :size => 5, id: "development-type-select" }        
      .field.mt-2.mb-3
        = f.label :Industry
        = f.select :industry, Project.industries.keys, { }, { class: "select2 form-control" }
      .field.mt-2.mb-3
        = f.label :Project_Diagram
        = f.input :image, required: true, direct_upload: true, as: :file
      .field.mt-2.mb-3
        = f.label :Start_date
        br
        = f.date_field :start_date
      .field.mt-2.mb-3
        = f.label :End_date
        br
        = f.date_field :end_date
      = f.button :submit, class: "btn btn-info mb-2"
      = link_to  "Back", :back, class:"btn btn-secondary mb-2 ml-4"
javascript:
  $('#frontend-select').select2();
  $('#backend-select').select2();
  $('#db-select').select2();
  $('#development-type-select').select2();

app/views/projects/edit.html.slim
h1
  | Editing Project
= render 'form', project: @project

app/views/projects/index.html.slim
.row
  .col-12
    .page-title-box
      .page-title-right
        ol.breadcrumb.m-0
          li.breadcrumb-item
            = link_to 'Home', root_path
          li.breadcrumb-item Projects
      h4.page-title
        | Project List

section.hero.is-primary.is-medium
  .hero-head
    nav.navbar
      .container
        .navbar-brand
        #navbarMenuHeroA.navbar-menu
          .navbar-end
            = link_to "Create New Project", new_project_path, class:"navbar-item"
  .hero-body
    .container.has-text-centered
      h1.title
        = yield :page_title

section.section
  .container
      .card
        .card-content
          .container
            .media
            .media-content
              .card-body
                h4.header-title.mb-2 About projects
                = form_tag("/projects", method: 'get') do               
                  .field.mb-3.float-md-right.mr-2
                    = select_tag(:development_type_ids, options_for_select(@development_type_options, :selected => @development_type ), {:prompt => "Development type",  onchange: "this.form.submit();"}) 
                  .field.mb-3.float-md-right.mr-2                    
                    = select_tag(:industry, options_for_select(Project.industries, :selected => @industry ), {:prompt => "Industry",  onchange: "this.form.submit();"}) 
                  .field.mb-3.float-md-right
                    span.header-title.mr-3 style=("font-weight: bold;") Filter:                
                .table-responsive-sm
                    table.table.table-centered.mb-0
                      tr
                        th scope="col" ID
                        th scope="col" Name
                        th scope="col" Start Date
                        th scope="col" End Date
                        th scope="col" HQ
                        th scope="col" Technology
                        th scope="col" Deployment
                        th scope="col" Developement
                        th scope="col" Industry
                        th scope="col" Website
                      - @projects.each do |p|
                          tr
                            td = p.id
                            td = link_to p.name, p
                            td = p.start_date
                            td = p.end_date
                            td = p.client.hq
                            td
                              - p.teches.each do |t|
                                = t.name
                                br
                            td = p.deployment
                            td 
                              - p.development_types.each do |t|
                                = t.name
                                br
                            td = p.industry
                            td = link_to p.website, p.website

section.section
  .container.mb-3
    .d-flex.justify-content-center
      - if @projects.size > 0
        == pagy_bootstrap_nav(@pagy)

app/views/projects/new.html.slim
- content_for :page_title, "Create a new project"
= render 'form'

app/views/projects/show.html.slim
.card
  h3.card-header
    = @project.name
  .card-body
    h5.card-title
      | Description
    p.card-text
      = @project.description
  .card-body
    h5.card-title
      | Frontend
    p.card-text
      - @project.teches.frontend.each do |t|
        = t.name
        br
  .card-body
    h5.card-title
      | Backend
    p.card-text
      - @project.teches.backend.each do |t|
        = t.name
        br
  .card-body
    h5.card-title
      | DB
    p.card-text
      - @project.teches.db.each do |t|
        = t.name
        br
  .card-body
    h5.card-title
      | Development type
    p.card-text
      - @project.development_types.each do |t|
        = t.name
        br
  .card-body
    h5.card-title
      | Industry
    p.card-text
      = @project.industry
  .card-body
    h5.card-title
        | Diagram
    - if @project.image.present?
      = image_tag @project.image, width: "300px"
  .card-body
    h5.card-title
      | Git repo
    p.card-text
      = link_to @project.git_repo, @project.git_repo
  .card-body
    h5.card-title
      | Trello
    p.card-text
      = link_to @project.trello, @project.trello
  .card-body
    h5.card-title
      | Developers list
    p.card-text
      - @project.developer_projects.each do |dp|
        - if dp.current?
          = link_to dp.developer.company_name, detail_developer_path(dp.developer)
          br
  .card-body
    h5.card-title
      | Management
    p.card-text
      - @project.pc_projects.each do |pp|
        = link_to pp.pc.company_name, pc_path(pp.pc)
        br
    .card-body
    h5.card-title
      | Start date
    p.card-text
      = @project.start_date
  .card-body
    h5.card-title
      | End date
    p.card-text
      = @project.end_date
  .card-body
    .level-right.d-flex
      p.level-item.mr-3
        = link_to '<i class="mdi mdi-pencil mr-1"></i> Edit'.html_safe, edit_project_path(@project), class:"button btn btn-primary btn-sm"
      p.level-item.mr-3
        = link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" }, class:"button btn btn-danger btn-sm"
      p.level-item
        = link_to  "Back", projects_path(page: @page), class:"button btn btn-dark btn-sm"
    - if @projects.size > 0
      .container.mb-3
        .d-flex.justify-content-center
          == pagy_bootstrap_nav(@pagy)