config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  resources :clients
  resources :developers do 
    get 'detail', on: :member
  end
  resources :projects
  resources :teches
  resources :careers do
    resources :job_submissions
  end
  devise_for :users
  resources :post_categories
  resources :posts

  get 'home', to: 'home#index'
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :post_categories, path: 'post-categories' do
        member do
          get 'filter-post-by-category', to: :filter_post_by_category
        end

        collection do
          get 'category-list', to: :category_list
        end
      end

      resources :posts, only: %i[index show] do
        member do
          get 'related-posts', to: :related_posts
        end
      end

      resources :careers, only: %i[index show]
      resources :job_submissions
      resources :subscriptions
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: posts
#
#  id                 :bigint           not null, primary key
#  deleted            :boolean          default(FALSE)
#  image_content_type :string
#  image_file_name    :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  meta_description   :string
#  meta_keyword       :string
#  meta_title         :string
#  post_type          :string
#  slug               :string
#  source             :string
#  title              :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  post_category_id   :bigint
#
# Indexes
#
#  index_posts_on_post_category_id  (post_category_id)
#  index_posts_on_slug              (slug) UNIQUE
#
class Post < ApplicationRecord
  extend FriendlyId
  include ConvertImageUrl
  has_many_attached :content

  friendly_id :title, use: :slugged

  after_create_commit :send_mail

  has_rich_text :content

  has_attached_file :image, preserve_files: true, styles: { medium: '300x300>', thumb: '100x100>' }

  validates_attachment_presence :image
  validates_attachment_content_type :image, presence: true, content_type: ['image/jpeg', 'image/gif', 'image/png']

  validates :content, presence: true
  validates :title, presence: true

  belongs_to :post_category

  scope :available, -> { where deleted: false }
  scope :search, lambda { |search_string|
    joins("INNER JOIN action_text_rich_texts ON action_text_rich_texts.record_id = posts.id AND record_type = 'Post'")
      .where('posts.title ILIKE ? OR action_text_rich_texts.body ILIKE ?', "%#{search_string}%", "%#{search_string}%")
  }

  def serializable_rich_content
    ActionController::Base.helpers.sanitize(ActionController::Base.helpers.raw(content))
  end

  private

  def send_mail
    list_emails = Subscription.list_email_subscription_posts.pluck(:email).uniq

    list_emails.each do |email|
      SubscriptionMailer.subscription_email_for_post(email, id).deliver_later
    end
  end
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < ApplicationController
      before_action :set_post, only: %i[show related_posts]
      before_action :prepare_posts, only: :related_posts

      def index
        pagy, posts = pagy(extract_post, items: per_page)

        links = {
          previous_page_url: pagenation_url(pagy.items, pagy.prev),
          next_page_url: pagenation_url(pagy.items, pagy.next)
        }

        render json: PostSerializer.new(posts, links: links)
      end

      def show
        render json: PostSerializer.new(@post)
      end

      def related_posts
        posts_closest = if @latest_posts.empty? || @oldest_posts.empty?
                          @oldest_posts.presence || @latest_posts
                        else
                          rank_posts(@latest_posts, @oldest_posts, @quality)
                        end

        render json: PostSerializer.new(posts_closest)
      end

      private

      def pagenation_url(pagy_items, pagy_page)
        return if pagy_page.blank?

        url = "#{original_url}?size=#{pagy_items}&page=#{pagy_page}"
        search_param = params[:search]

        return url if search_param.blank?

        "#{url}&search=#{search_param}"
      end

      def original_url
        request.original_url[/\A[^?]+/]
      end

      def set_post
        @post = Post.friendly.find(params[:id])
      end

      def rank_posts(latest_posts, oldest_posts, num_limited)
        latest_posts_length = latest_posts.length
        oldest_posts_length = oldest_posts.length

        if latest_posts_length == num_limited
          latest_posts[1..-1] + oldest_posts[0..0]
        elsif (latest_posts_length + oldest_posts_length) <= num_limited
          latest_posts + oldest_posts
        else
          position = (num_limited - latest_posts_length - 1)
          latest_posts + oldest_posts[0..position]
        end
      end

      def prepare_posts
        @quality = params[:num_limited].presence || 3

        posts = Post.available.order(id: :desc)
        @latest_posts = posts.where('id > ?', @post.id).last(@quality)
        @oldest_posts = posts.where('id < ?', @post.id).first(@quality)
      end

      def extract_post
        return Post.available.search(params[:search]) if params[:search]

        Post.available.order(id: :desc)
      end
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_post_category_options, only: %i[new create edit update]

  def index
    @pagy, @posts = pagy(extract_post, items: per_page)
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save!
        format.html { redirect_to @post, notice: 'Post was successfully created.'}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.update(deleted: true)

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def set_post_category_options
    @post_category_options = PostCategory.pluck(:title, :id)
  end

  def post_params
    params.require(:post).permit(:post_category_id, :title, :content, :image,
                                 :source, :post_type, :meta_title,
                                 :meta_keyword, :meta_description)
  end

  def extract_post
    return Post.available.search(params[:search]) if params[:search]

    Post.available.order(id: :desc)
  end
end

app/views/posts/_form.html.slim
.section
  = simple_form_for @post do |f|
    .field.mt-2.mb-3
      .control
        = f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-2
      = f.label :category
      .control
        = f.select :post_category_id, @post_category_options
    .field.mt-2.mb-3
      = f.label :content
      = f.text_area :content, 'data-provider': :summernote, class: 'form-control'
    = f.input :image, required: true, direct_upload: true, as: :file
    .field.mt-2.mb-3
      .control
        = f.input :meta_title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
      .control
        = f.input :meta_keyword, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-3
      .control
        = f.input :meta_description, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-2
      .control
        = f.input :source, label: 'Source :', input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    .field.mt-2.mb-2
      .control
        = f.input :post_type, label: 'Type :', input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' }
    = f.button :submit, class: "btn btn-info mb-2"
    = link_to  "Back", :back, class:"btn btn-secondary mb-2 ml-4"

app/views/posts/edit.html.slim
- content_for :page_title, "Edit Blog"
= render 'form'

app/views/posts/index.html.slim
.row
  .col-12
    .page-title-box
      .page-title-right
        ol.breadcrumb.m-0
          li.breadcrumb-item
            = link_to 'Home', root_path
          li.breadcrumb-item Blog
      h4.page-title Blog

section.hero.is-primary.is-medium
  .hero-head
    nav.navbar
      .container
        .navbar-brand
        #navbarMenuHeroA.navbar-menu
          .navbar-end
            = link_to "Create New Blog", new_post_path, class:"navbar-item"
  .hero-body
    .container.has-text-centered
      h1.title
        = yield :page_title

section.section
  .container
    - @posts.each do |post|
      .card
        .card-content
          .container
            .media
            .media-content
              h5.title.is-4
                = link_to post.title, post
            .media-content
              h5 Blog Category:
              h6.title.is-4
                = post.post_category&.title
            .media-content
              h5 Meta Title:
              h6.title.is-4
                = post.meta_title
            .media-content
              h5 Meta Keyword:
              h6.title.is-4
                = post.meta_keyword
            .media-content
              h5 Meta Description:
              h6.title.is-4
                = post.meta_description
            .media-content
              h5 Source:
              h6.title.is-4
                = post.source
            .media-content
              h5 Type:
              h6.title.is-4
                = post.post_type
            .content.mb-1
              / = raw post.content
        .container.mt-2.mb-4
          - if post.image.present?
              = image_tag post.image_url(:medium)

section.section
  .container.mb-3
    .d-flex.justify-content-center
      - if @posts.size > 0
          == pagy_bootstrap_nav(@pagy)

app/views/posts/new.html.slim
- content_for :page_title, "Create a new blog"
= render 'form'

app/views/posts/show.html.slim
- content_for :page_title, @post.title
section.section
  .container.mb-4
    nav.level
      /! Left side
      .level-left.mt-2
        p.level-item
          strong Actions
      /! Right side
      .level-right.d-flex
        p.level-item.mr-3
          = link_to "Edit", edit_post_path(@post), class:"button btn btn-primary btn-sm"
        p.level-item.mr-3
          = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button btn btn-danger btn-sm"
        p.level-item
          = link_to  "Back", posts_path(page: @page), class:"button btn btn-dark btn-sm"
    hr/
    | Title:
    h4.title
      = @post.title
    | Category:
    h4.title
      = @post.post_category&.title
    | Meta Title:
    h5.title
      = @post.meta_title
    | Meta Keyword:
    h5.title
      = @post.meta_keyword
    | Meta Description:
    h5.title
      = @post.meta_description
    | Source:
    h5.title
      = @post.source
    | Type:
    h5.title
      = @post.post_type
    | Content:
    .content.mb-2
      = sanitize raw(@post.content)

  - if @post.image.present?
    = image_tag @post.image_url(:medium)